export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";
export const RANDOMINCREMENT = "RANDOMINCREMENT";
export const RANDOMDECREMENT = "RANDOMDECREMENT";